var map = new GMap2(document.getElementById("dnn_ctr385_MainDisplay_divMap"));
map.addControl(new GSmallMapControl());
map.addControl(new GMapTypeControl());
function displayMap(){
    var mapDiv = document.getElementById('dnn_ctr385_MainDisplay_divMap');
    mapDiv.style.display = '';
}

function showLocation(latitude, longitude, index, address, title, labelId){
    map.clearOverlays();
    var marker = createLocationMarker(latitude, longitude, index + 1, title + '<br />' + address);
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    var allLabel = document.getElementById('dnn_ctr385_MainDisplay_lblLocatorMapLabel');
    allLabel.style.display = 'none';
    var label = document.getElementById('locatorMapLabel');
    label.style.display = '';
    label.innerHTML = title + '<br />' + address.replace("%%", "<br />");
    var scrollLabel = document.getElementById('dnn_ctr385_MainDisplay_lblScrollToViewMore');
    scrollLabel.style.display = '';
    var mapLink = document.getElementById('lblMapLink');
    mapLink.style.display = '';
    var lnkDrivingDirections = document.getElementById('lnkDrivingDirections');
    var mapLoc = 'http://maps.google.com/maps?f=q&hl=en&geocode=&q=' + address;
    lnkDrivingDirections.href = mapLoc.replace("%%", " ");
    var currentlyMappedLabel = document.getElementById(labelId);
    var currentlyMappedLabels = getElementsByClassName('currentlyMapped', 'span', document.getElementById('dnn_ctr385_MainDisplay_rptLocations'));
    var length = currentlyMappedLabels.length;
    displayMap();
    map.checkResize();
    map.setCenter(myPoint, 13);
    for (var i = 0; i < length; i++) {
        currentlyMappedLabels[i].className = 'hideCurrentlyMapped';
    }
    currentlyMappedLabel.className = 'currentlyMapped';
}

function showAllLocations(){
    var arr = new Array();
    var marker;
    map.clearOverlays();
    marker = createLocationMarker(38.574993, -90.29489, 1, 'SOUTHSIDE  HARDWARE<br/>6401 HAMPTON AVE<br/>ST LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[0] = marker;
    marker = createLocationMarker(38.600803, -90.25568, 2, 'OAK HILL TRUE VALUE<br/>4100 CONNECTICUT ST<br/>ST LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[1] = marker;
    marker = createLocationMarker(38.557394, -90.26048, 3, 'LOWE\'S OF S. SAINT LOUIS, MO<br/>932 LOUGHBOROUGH AVENUE<br/>SAINT LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[2] = marker;
    marker = createLocationMarker(38.613089, -90.317955, 4, 'SCHEIDT HARDWARE CO<br/>7320 MANCHESTER<br/>MAPLEWOOD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[3] = marker;
    marker = createLocationMarker(38.528046, -90.286012, 5, 'SEARS<br/>3160 TELEGRAPH ROAD<br/>SAINT LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[4] = marker;
    marker = createLocationMarker(38.617179, -90.33356, 6, 'LOWE\'S OF MAPLEWOOD, MO<br/>2300 MAPLEWOOD COMMONS DR<br/>MAPLEWOOD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[5] = marker;
    marker = createLocationMarker(38.616866, -90.334319, 7, 'WAL-MART<br/>1900 MAPLEWOOD COMMONS DRIVE<br/>MAPLEWOOD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[6] = marker;
    marker = createLocationMarker(38.625817, -90.334978, 8, 'HOME DEPOT<br/>1603 S HANLEY RD<br/>BRENTWOOD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[7] = marker;
    marker = createLocationMarker(38.64099, -90.325769, 9, 'SEARS<br/>15 CRESTWOOD PLAZA<br/>SAINT LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[8] = marker;
    marker = createLocationMarker(38.495016, -90.298438, 10, 'WAL-MART<br/>3270 TELEGRAPH ROAD<br/>ST LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[9] = marker;
    marker = createLocationMarker(38.476932, -90.305058, 11, 'HANDYMAN TRUE VALUE HARDWARE<br/>5405 TELEGRAPH RD<br/>ST LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[10] = marker;
    marker = createLocationMarker(38.562588, -90.406805, 12, 'WAL-MART<br/>1202 SO. KIRKWOOD ROAD<br/>KIRKWOOD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[11] = marker;
    marker = createLocationMarker(38.562396, -90.406809, 13, 'LOWE\'S OF KIRKWOOD, MO.<br/>1212 SOUTH KIRKWOOD ROAD<br/>KIRKWOOD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[12] = marker;
    marker = createLocationMarker(38.553612, -90.409464, 14, 'HOME DEPOT<br/>10890 SUNSET HILLS PLAZA<br/>SAINT LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[13] = marker;
    marker = createLocationMarker(38.701558, -90.293205, 15, 'SCHULTE HDWE & SPLY CO INC<br/>7204 NATURAL BRIDGE RD<br/>ST. LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[14] = marker;
    marker = createLocationMarker(38.686487, -90.355161, 16, 'HOME DEPOT<br/>8901 PAGE AVENUE<br/>OVERLAND');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[15] = marker;
    marker = createLocationMarker(38.51, -90.437426, 17, 'WAL-MART<br/>653 GRAVOIS BLUFFS BLVD<br/>FENTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[16] = marker;
    marker = createLocationMarker(38.509596, -90.446149, 18, 'LOWE\'S OF FENTON, MO.<br/>1 GRAVOIS BLUFFS PLAZA DRIVE<br/>FENTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[17] = marker;
    marker = createLocationMarker(38.43828, -90.37673, 19, 'WAL-MART<br/>2201 MICHIGAN AVENUE<br/>ARNOLD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[18] = marker;
    marker = createLocationMarker(38.596495, -90.484101, 20, 'WAL-MART<br/>13901 MANCHESTER RD<br/>TOWN AND COUNTRY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[19] = marker;
    marker = createLocationMarker(38.596587, -90.485944, 21, 'HOME DEPOT<br/>13929 MANCHESTER RD<br/>TOWN AND COUNTRY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[20] = marker;
    marker = createLocationMarker(38.73392, -90.392414, 22, 'WAL-MART<br/>10835 ST CHARLES ROCK ROAD<br/>ST. ANN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[21] = marker;
    marker = createLocationMarker(38.593872, -90.502516, 23, 'HOME DEPOT<br/>14205 MANCHESTER RD<br/>MANCHESTER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[22] = marker;
    marker = createLocationMarker(38.765985, -90.280644, 24, 'WAL-MART<br/>10741 WEST FLORISSANT<br/>FERGUSON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[23] = marker;
    marker = createLocationMarker(38.76911, -90.264759, 25, 'HOME DEPOT<br/>10930 NEW HALLS FERRY RD<br/>FERGUSON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[24] = marker;
    marker = createLocationMarker(38.739736, -90.398661, 26, 'HOME DEPOT<br/>11215 ST CHARLES ROCK RD<br/>BRIDGETON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[25] = marker;
    marker = createLocationMarker(38.741103, -90.403778, 27, 'BRANNEKY TRUE VALUE HDWE<br/>11403 SAINT CHARLES ROCK RD<br/>BRIDGETON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[26] = marker;
    marker = createLocationMarker(38.413087, -90.394753, 28, 'HOME DEPOT<br/>3865 VOGEL RD<br/>ARNOLD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[27] = marker;
    marker = createLocationMarker(38.746765, -90.424834, 29, 'LOWE\'S OF BRIDGETON, MO<br/>11974 PAUL MAYER AVENUE<br/>BRIDGETON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[28] = marker;
    marker = createLocationMarker(38.591579, -90.541212, 30, 'LOWE\'S OF BALLWIN, MO<br/>14810 MANCHESTER ROAD<br/>BALLWIN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[29] = marker;
    marker = createLocationMarker(38.795764, -90.337211, 31, 'HANDYMAN TRUE VALUE HARDWARE<br/>500 W WASHINGTON ST<br/>FLORISSANT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[30] = marker;
    marker = createLocationMarker(38.797493, -90.338284, 32, 'SEARS<br/>455 N HWY 67<br/>FLORISSANT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[31] = marker;
    marker = createLocationMarker(38.805574, -90.296626, 33, 'HOME DEPOT<br/>13915 NEW HALLS FERRY RD<br/>FLORISSANT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[32] = marker;
    marker = createLocationMarker(38.482199, -90.529366, 34, 'SEARS<br/>400 DILLON PLAZA<br/>HIGH RIDGE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[33] = marker;
    marker = createLocationMarker(38.810371, -90.296782, 35, 'LOWE\'S OF FLORISSANT, MO<br/>3180 NORTH HIGHWAY 67<br/>FLORISSANT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[34] = marker;
    marker = createLocationMarker(38.592797, -90.563896, 36, 'SEARS<br/>15425 MANCHESTER RD, SUITE 20<br/>BALLWIN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[35] = marker;
    marker = createLocationMarker(38.821833, -90.247826, 37, 'SEARS<br/>100 JAMESTOWN MALL<br/>FLORISSANT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[36] = marker;
    marker = createLocationMarker(38.65439, -90.564011, 38, 'SEARS<br/>CHESTERFIELD CENTER, 1 CHESTERFIELD MALL<br/>CHESTERFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[37] = marker;
    marker = createLocationMarker(38.590571, -90.607998, 39, 'HOME DEPOT<br/>37 ELLISVILLE TOWNE CTRE<br/>ELLISVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[38] = marker;
    marker = createLocationMarker(38.666412, -90.590911, 40, 'WAL-MART<br/>100 THF BLVD<br/>CHESTERFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[39] = marker;
    marker = createLocationMarker(38.666309, -90.601775, 41, 'LOWE\'S OF CHESTERFIELD, MO.<br/>290 THF BLVD<br/>CHESTERFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[40] = marker;
    marker = createLocationMarker(38.667385, -90.606008, 42, 'HOME DEPOT<br/>390 THF BOULEVARD<br/>CHESTERFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[41] = marker;
    marker = createLocationMarker(38.783994, -90.524883, 43, 'WAL-MART<br/>2897 VETERAN\'S MEMORIAL PKWY<br/>ST. CHARLES');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[42] = marker;
    marker = createLocationMarker(38.786321, -90.528706, 44, 'LOWE\'S OF ST. CHARLES, MO<br/>2900 WEST CLAY STREET<br/>SAINT CHARLES');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[43] = marker;
    marker = createLocationMarker(38.409394, -90.574456, 45, 'WAL-MART<br/>4550 GRAVOIS ROAD<br/>HOUSE SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[44] = marker;
    marker = createLocationMarker(38.505865, -90.641246, 46, 'DICKEY BUB TRUE VALUE<br/>100 HILLTOP VILLAGE CENTER DRIVE<br/>EUREKA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[45] = marker;
    marker = createLocationMarker(38.791032, -90.565516, 47, 'HOME DEPOT<br/>3891 MEXICO RD<br/>SAINT CHARLES');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[46] = marker;
    marker = createLocationMarker(38.80281, -90.628132, 48, 'SCHNEIDER TRUE VALUE IMPLEMENT<br/>9 MAIN ST<br/>ST PETERS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[47] = marker;
    marker = createLocationMarker(38.213124, -90.390468, 49, 'WAL-MART<br/>650 SOUTH TRUMAN BLVD<br/>FESTUS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[48] = marker;
    marker = createLocationMarker(38.758669, -90.700198, 50, 'SEARS<br/>2947 HWY K<br/>O FALLON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[49] = marker;
    marker = createLocationMarker(38.211748, -90.403446, 51, 'HOME DEPOT<br/>1131 W GANNON<br/>FESTUS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[50] = marker;
    marker = createLocationMarker(38.212064, -90.408543, 52, 'LOWE\'S OF FESTUS, MO<br/>1111 BRADLEY STREET<br/>FESTUS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[51] = marker;
    marker = createLocationMarker(38.792248, -90.69504, 53, 'LOWE\'S OF O\'FALLON, MO.<br/>8501 MEXICO ROAD<br/>ST PETERS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[52] = marker;
    marker = createLocationMarker(38.786898, -90.699776, 54, 'HOME DEPOT<br/>1525 HWY K<br/>O FALLON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[53] = marker;
    marker = createLocationMarker(38.790555, -90.699004, 55, 'WAL-MART<br/>1307 HIGHWAY K<br/>O`FALLON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[54] = marker;
    marker = createLocationMarker(38.797698, -90.700342, 56, 'HOMETOWN TRUE VALUE HWE & GIFT<br/>921 HIGHWAY K<br/>OFALLON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[55] = marker;
    marker = createLocationMarker(38.76836, -90.78496, 57, 'LOWE\'S OF LAKE ST. LOUIS, MO<br/>6302 RONALD REAGAN DRIVE<br/>LAKE SAINT LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[56] = marker;
    marker = createLocationMarker(38.773868, -90.783146, 58, 'WAL-MART<br/>6100 RONALD REAGAN DRIVE<br/>LAKE ST. LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[57] = marker;
    marker = createLocationMarker(38.164481, -90.570072, 59, 'DEP BUILDERS SUPPLY/DEP HEATING & COOLING<br/>12561 HWY 21<br/>DE SOTO');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[58] = marker;
    marker = createLocationMarker(38.821677, -90.851499, 60, 'WAL-MART<br/>1971 WENTZVILLE PKWY<br/>WENTZVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[59] = marker;
    marker = createLocationMarker(38.821808, -90.852667, 61, 'HOME DEPOT<br/>1920 WENTZVILLE PKWY<br/>WENTZVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[60] = marker;
    marker = createLocationMarker(38.822202, -90.85323, 62, 'LOWE\'S OF WENTZVILLE, MO<br/>1889 WENTZVILLE PARKWAY<br/>WENTZVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[61] = marker;
    marker = createLocationMarker(38.114651, -90.556729, 63, 'WAL-MART<br/>12862 STATE ROAD 21<br/>DE SOTO');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[62] = marker;
    marker = createLocationMarker(38.808176, -90.882677, 64, 'CHARLIE\'S FARM & HOME TRUE VALUE<br/>1583 W PEARCE BLVD<br/>WENTZVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[63] = marker;
    marker = createLocationMarker(38.990562, -90.747475, 65, 'RIVER CITY TRUE VALUE HARDWARE<br/>4041 E HWY 47<br/>WINFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[64] = marker;
    marker = createLocationMarker(38.433428, -90.972229, 66, 'WAL-MART<br/>1445 E CENTRAL<br/>UNION');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[65] = marker;
    marker = createLocationMarker(37.967879, -90.046708, 67, 'A & K TRUE VALUE<br/>601 STE GENEVIEVE DR<br/>SAINTE GENEVIEVE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[66] = marker;
    marker = createLocationMarker(38.98651, -90.96454, 68, 'WAL-MART<br/>101 HWY 47 EAST<br/>TROY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[67] = marker;
    marker = createLocationMarker(38.803648, -91.139248, 69, 'WAL-MART<br/>500 WARREN COUNTY CENTER<br/>WARRENTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[68] = marker;
    marker = createLocationMarker(37.87464, -90.512364, 70, 'WAL-MART<br/>407 NO. STATE ST<br/>DESLOGE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[69] = marker;
    marker = createLocationMarker(38.004238, -90.859358, 71, 'WAL-MART<br/>1701 A. ROY DRIVE<br/>WASHINGTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[70] = marker;
    marker = createLocationMarker(37.791124, -90.433408, 72, 'LOWE\'S OF FARMINGTON, MO<br/>625 WEST KARSCH BOULEVARD<br/>FARMINGTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[71] = marker;
    marker = createLocationMarker(37.78694, -90.435766, 73, 'WAL-MART<br/>701 WALTON DRIVE<br/>FARMINGTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[72] = marker;
    marker = createLocationMarker(38.152162, -91.249358, 74, 'BOURBON TRUE VALUE FAMILY CTR<br/>140 WEST PINE<br/>BOURBON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[73] = marker;
    marker = createLocationMarker(37.725801, -89.862434, 75, 'ROZIER TRUE VALUE<br/>2 E SAINTE MARIES ST<br/>PERRYVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[74] = marker;
    marker = createLocationMarker(37.703298, -89.895017, 76, 'WAL-MART<br/>1750 S. PERRYVILLE<br/>PERRYVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[75] = marker;
    marker = createLocationMarker(38.327834, -91.532588, 77, 'WAL-MART<br/>1888 HWY 28 EAST<br/>OWENSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[76] = marker;
    marker = createLocationMarker(38.07268, -91.404706, 78, 'WAL-MART<br/>100 OZARK DR<br/>CUBA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[77] = marker;
    marker = createLocationMarker(38.977646, -91.505145, 79, 'MONTGOMERY TRUE VALUE HARDWARE<br/>221 N STURGEON ST<br/>MONTGOMERY CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[78] = marker;
    marker = createLocationMarker(39.240043, -91.482036, 80, 'BRENEMAN - ENNIS HARDWARE<br/>902 W HWY 54<br/>VANDALIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[79] = marker;
    marker = createLocationMarker(37.366565, -89.638007, 81, 'WAL-MART<br/>3051 EAST JACKSON BLVD.<br/>JACKSON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[80] = marker;
    marker = createLocationMarker(37.967181, -91.764108, 82, 'LOWE\'S OF ROLLA, MO.<br/>2300 NORTH BISHOP AVENUE<br/>ROLLA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[81] = marker;
    marker = createLocationMarker(38.863049, -91.943905, 83, 'WAL-MART<br/>1701 NORTH BLUFF STREET<br/>FULTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[82] = marker;
    marker = createLocationMarker(37.953134, -91.775113, 84, 'FAMILY CENTER TRUE VALUE & V&S<br/>1200 E STATE ROUTE 72<br/>ROLLA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[83] = marker;
    marker = createLocationMarker(37.939158, -91.777318, 85, 'WAL-MART<br/>500 SOUTH BISHOP<br/>ROLLA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[84] = marker;
    marker = createLocationMarker(37.636126, -91.547253, 86, 'WAL-MART<br/>1101 HWY 32 WEST<br/>SALEM');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[85] = marker;
    marker = createLocationMarker(39.152723, -91.887736, 87, 'WAL-MART<br/>4820 SO. CLARK ST<br/>MEXICO');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[86] = marker;
    marker = createLocationMarker(37.296616, -89.580504, 88, 'LOWE\'S OF CAPE GIRARDEAU, MO.<br/>3440 LOWES DRIVE<br/>CAPE GIRARDEAU');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[87] = marker;
    marker = createLocationMarker(37.296372, -89.579575, 89, 'SEARS<br/>330 SIEMERS DRIVE<br/>CAPE GIRARDEAU');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[88] = marker;
    marker = createLocationMarker(39.71965, -91.392033, 90, 'MARTINS TRUE VALUE HDW<br/>4215 MCMASTERS AVE<br/>HANNIBAL');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[89] = marker;
    marker = createLocationMarker(39.722682, -91.39385, 91, 'WAL-MART<br/>3650 STARDUST DRIVE<br/>HANNIBAL');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[90] = marker;
    marker = createLocationMarker(37.14039, -90.699109, 92, 'WAL-MART<br/>#15 HALS PLAZA DR<br/>PIEDMONT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[91] = marker;
    marker = createLocationMarker(38.58132, -92.21578, 93, 'WAL-MART<br/>724 STADIUM WEST BLVD<br/>JEFFERSON CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[92] = marker;
    marker = createLocationMarker(38.582183, -92.249391, 94, 'LOWE\'S OF JEFFERSON CITY, MO<br/>3441 MISSOURI BLVD<br/>JEFFERSON CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[93] = marker;
    marker = createLocationMarker(37.991807, -92.095371, 95, 'TRI-COUNTY TRUE VALUE<br/>205 W 2ND ST<br/>DIXON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[94] = marker;
    marker = createLocationMarker(39.211402, -92.137759, 96, 'RITCHIE & SONS TRUE VALUE<br/>105 W SINGLETON<br/>CENTRALIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[95] = marker;
    marker = createLocationMarker(38.96377, -92.289369, 97, 'HOME DEPOT<br/>3215 CLARK LANE<br/>COLUMBIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[96] = marker;
    marker = createLocationMarker(38.951732, -92.293661, 98, 'LOWE\'S OF COLUMBIA, MO.<br/>201 CONLEY ROAD.<br/>COLUMBIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[97] = marker;
    marker = createLocationMarker(38.954121, -92.293523, 99, 'WAL-MART<br/>415 CONLEY ROAD<br/>COLUMBIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[98] = marker;
    marker = createLocationMarker(38.913269, -92.309741, 100, 'WAL-MART<br/>1201 GRINDSTONE PKWY<br/>COLUMBIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[99] = marker;
    marker = createLocationMarker(37.499291, -91.858298, 101, 'FRIEND TRUE VALUE LBR<br/>145 W HWY 32<br/>LICKING');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[100] = marker;
    marker = createLocationMarker(37.823502, -92.150336, 102, 'WAL-MART<br/>185 ST ROBERT BLVD<br/>SAINT ROBERT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[101] = marker;
    marker = createLocationMarker(37.828151, -92.176013, 103, 'FIELDS TRUE VALUE HARDWARE & LUMBER<br/>512 CITY ROUTE 66<br/>SAINT ROBERT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[102] = marker;
    marker = createLocationMarker(38.954803, -92.382077, 104, 'WAL-MART<br/>3001 W. BROADWAY<br/>COLUMBIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[103] = marker;
    marker = createLocationMarker(39.239756, -92.279687, 105, 'RITCHIE & SONS TRUE VALUE<br/>113 N OGDEN ST<br/>STURGEON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[104] = marker;
    marker = createLocationMarker(36.803722, -89.977319, 106, 'WAL-MART<br/>2025 BUS. HWY 60 WEST<br/>DEXTER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[105] = marker;
    marker = createLocationMarker(36.865278, -89.581815, 107, 'LOWE\'S OF SIKESTON, MO<br/>1240 S. MAIN STREET<br/>SIKESTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[106] = marker;
    marker = createLocationMarker(36.865054, -89.581944, 108, 'WAL-MART<br/>1303 SOUTH MAIN<br/>SIKESTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[107] = marker;
    marker = createLocationMarker(36.755912, -90.408064, 109, 'WAL-MART<br/>333 S WESTWOOD<br/>POPLAR BLUFF');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[108] = marker;
    marker = createLocationMarker(36.753081, -90.409033, 110, 'HOME DEPOT<br/>639 S WESTWOOD BLVD<br/>POPLAR BLUFF');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[109] = marker;
    marker = createLocationMarker(37.312575, -91.96038, 111, 'WAL-MART<br/>1433 SO. SAM HOUSTON BLVD<br/>HOUSTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[110] = marker;
    marker = createLocationMarker(36.738989, -90.419636, 112, 'MILLS IRON & SUPPLY CO<br/>1919 S WESTWOOD BLVD<br/>POPLAR BLUFF');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[111] = marker;
    marker = createLocationMarker(39.45507, -92.378238, 113, 'WAL-MART<br/>1301 HWY 24 EAST<br/>MOBERLY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[112] = marker;
    marker = createLocationMarker(38.149242, -92.59854, 114, 'LOWE\'S OF OSAGE BEACH, MO<br/>950 HIGHWAY 42<br/>OSAGE BEACH');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[113] = marker;
    marker = createLocationMarker(38.154152, -92.612981, 115, 'HOME DEPOT<br/>4030 HWY 54<br/>OSAGE BEACH');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[114] = marker;
    marker = createLocationMarker(38.147707, -92.620897, 116, 'WAL-MART<br/>4252 HWY 54<br/>OSAGE BEACH');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[115] = marker;
    marker = createLocationMarker(36.997973, -91.687358, 117, 'BUSH & SANDERS TV HARDWARE<br/>417 EAST ST<br/>MOUNTAIN VIEW');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[116] = marker;
    marker = createLocationMarker(38.957338, -92.740774, 118, 'WAL-MART<br/>1920 MAIN STREET<br/>BOONVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[117] = marker;
    marker = createLocationMarker(39.752098, -92.465815, 119, 'WAL-MART<br/>705 EAST BRIGGS DRIVE<br/>MACON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[118] = marker;
    marker = createLocationMarker(37.821116, -92.725143, 120, 'LOWE\'S OF LEBANON, MO<br/>190 EAST HIGHWAY 32<br/>LEBANON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[119] = marker;
    marker = createLocationMarker(37.663404, -92.649464, 121, 'WAL-MART<br/>1800 S JEFFERSON<br/>LEBANON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[120] = marker;
    marker = createLocationMarker(37.679586, -92.662538, 122, 'FARMERS TRUE VALUE EXCHANGE<br/>225 S JEFFERSON AVE<br/>LEBANON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[121] = marker;
    marker = createLocationMarker(37.153462, -92.262987, 123, 'WAL-MART<br/>2100 NORTH MAIN<br/>MOUNTAIN GROVE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[122] = marker;
    marker = createLocationMarker(37.399897, -92.606938, 124, 'MFA TRUE VALUE<br/>2135 HIGHWAY M<br/>GROVESPRING');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[123] = marker;
    marker = createLocationMarker(36.523686, -91.532713, 125, 'WAL-MART<br/>333 EAST WALNUT<br/>THAYER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[124] = marker;
    marker = createLocationMarker(36.524381, -91.539418, 126, 'FORSCHLER TRUE VALUE<br/>117 S SECOND ST<br/>THAYER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[125] = marker;
    marker = createLocationMarker(36.268169, -89.90868, 127, 'WAL-MART<br/>1500 EAST FIRST ST<br/>KENNETT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[126] = marker;
    marker = createLocationMarker(38.709789, -93.268749, 128, 'WAL-MART<br/>3201 WEST BROADWAY<br/>SEDALIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[127] = marker;
    marker = createLocationMarker(36.236502, -90.069292, 129, 'BURKE TRUE VALUE HDW<br/>1207 ST FRANCIS ST<br/>KENNETT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[128] = marker;
    marker = createLocationMarker(38.711647, -93.273887, 130, 'LOWE\'S OF SEDALIA, MO.<br/>3811 WEST BROADWAY<br/>SEDALIA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[129] = marker;
    marker = createLocationMarker(36.418846, -89.057918, 131, 'DICKEY BUB TRUE VALUE<br/>1 UNION PLAZA<br/>UNION');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[130] = marker;
    marker = createLocationMarker(39.714351, -92.951257, 132, 'C&W TRUE VALUE HARDWARE<br/>110 S KANSAS AVE<br/>MARCELINE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[131] = marker;
    marker = createLocationMarker(40.45532, -92.169395, 133, 'MEMPHIS FARM AND HOME<br/>463 SOUTH MARKET<br/>MEMPHIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[132] = marker;
    marker = createLocationMarker(40.209921, -92.582584, 134, 'TRUE VALUE FARM & HOME<br/>100 W POTTER<br/>KIRKSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[133] = marker;
    marker = createLocationMarker(40.213736, -92.581989, 135, 'WAL-MART<br/>2206 NORTH BALTIMORE<br/>KIRKSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[134] = marker;
    marker = createLocationMarker(37.640594, -93.106235, 136, 'WAL-MART<br/>1250 WEST DALLAS<br/>BUFFALO');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[135] = marker;
    marker = createLocationMarker(37.154464, -92.754024, 137, '4-STAR TRUE VALUE BLDG CTR<br/>455 HWY C<br/>SEYMOUR');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[136] = marker;
    marker = createLocationMarker(38.249973, -93.369668, 138, 'WARSAW TRUE VALUE<br/>28970 COMMERCIAL AVENUE<br/>WARSAW');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[137] = marker;
    marker = createLocationMarker(39.770771, -93.07019, 139, 'WAL-MART<br/>937 PARK CIRCLE DR<br/>BROOKFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[138] = marker;
    marker = createLocationMarker(38.963681, -93.418876, 140, 'BERNARD TRUE VALUE LBR & HDW<br/>200 SPRING ST<br/>SWEET SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[139] = marker;
    marker = createLocationMarker(36.961146, -92.667904, 141, 'COOPER TRUE VALUE HDW<br/>1101 NW 12TH AVE<br/>AVA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[140] = marker;
    marker = createLocationMarker(36.962307, -92.676931, 142, 'WAL-MART<br/>1309 NW 12TH AVE<br/>AVA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[141] = marker;
    marker = createLocationMarker(37.294351, -92.997021, 143, 'WAL-MART<br/>14740 STATE HWY #38<br/>MARSHFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[142] = marker;
    marker = createLocationMarker(36.063435, -89.709521, 144, 'WAL-MART<br/>STATE HWY 84 WEST<br/>CARUTHERSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[143] = marker;
    marker = createLocationMarker(37.590757, -93.401518, 145, 'WAL-MART<br/>2451 S. SPRINGFIELD<br/>BOLIVAR');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[144] = marker;
    marker = createLocationMarker(37.583405, -93.397981, 146, 'WB #107 C&C FARM & HOME SUPPLY<br/>3260 S SPRINGFIELD AVE<br/>BOLIVAR');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[145] = marker;
    marker = createLocationMarker(37.24143, -93.259019, 147, 'WAL-MART<br/>1923 EAST KEARNEY ST<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[146] = marker;
    marker = createLocationMarker(38.778949, -93.735786, 148, 'WAL-MART<br/>301 E. COOPER AVENUE<br/>WARRENSBURG');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[147] = marker;
    marker = createLocationMarker(38.777399, -93.736703, 149, 'WB #208 FARM & HOME OF WARRENSBURG<br/>907 N SIMPSON DRIVE<br/>WARRENSBURG');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[148] = marker;
    marker = createLocationMarker(38.763011, -93.7381, 150, 'TRUE VALUE HARDWARE<br/>101 N COLLEGE AVE<br/>WARRENSBURG');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[149] = marker;
    marker = createLocationMarker(38.768418, -93.737801, 151, 'LOWE\'S OF WARRENSBURG, MO<br/>912 NORTH COLLEGE AVENUE<br/>WARRENSBURG');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[150] = marker;
    marker = createLocationMarker(37.200656, -93.235121, 152, 'WAL-MART<br/>3315 SOUTH CAMPBELL<br/>SPRINGFIELD (SW)');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[151] = marker;
    marker = createLocationMarker(38.366226, -93.749332, 153, 'WAL-MART<br/>1712 EAST OHIO<br/>CLINTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[152] = marker;
    marker = createLocationMarker(38.366489, -93.76277, 154, 'FULL LINE LUMBER CENTER<br/>802 E OHIO<br/>CLINTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[153] = marker;
    marker = createLocationMarker(39.076808, -93.733503, 155, 'WAL-MART<br/>1180 W. 19TH STTREET<br/>HIGGINSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[154] = marker;
    marker = createLocationMarker(37.25305, -93.312619, 156, 'LOWE\'S OF N. SPRINGFIELD, MO.<br/>1707 WEST NORTON ROAD<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[155] = marker;
    marker = createLocationMarker(37.248739, -93.310834, 157, 'WAL-MART<br/>2825 N KANSAS EXPRESSWAY<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[156] = marker;
    marker = createLocationMarker(37.16283, -93.263313, 158, 'SEARS<br/>2825 S GLENSTONE<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[157] = marker;
    marker = createLocationMarker(37.149888, -93.261627, 159, 'LOWE\'S OF SPRINGFIELD, MO.<br/>1850 E. PRIMROSE<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[158] = marker;
    marker = createLocationMarker(37.141407, -93.255553, 160, 'HOME DEPOT<br/>2104 E INDEPENDENCE<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[159] = marker;
    marker = createLocationMarker(38.260547, -93.771929, 161, 'QUALITY TRUE VALUE FARM&HOME<br/>109 S SECOND ST<br/>DEEPWATER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[160] = marker;
    marker = createLocationMarker(37.142469, -93.258263, 162, 'WAL-MART<br/>2021 EAST INDEPENDENCE<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[161] = marker;
    marker = createLocationMarker(39.775282, -93.541909, 163, 'LOWE\'S OF CHILLICOTHE, MO<br/>100 WEST BUSINESS 36<br/>CHILLICOTHE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[162] = marker;
    marker = createLocationMarker(37.140023, -93.323613, 164, 'SPRINGFIELD TRUE VALUE<br/>4121 SOUTH COX<br/>SPRINGFIELD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[163] = marker;
    marker = createLocationMarker(39.777323, -93.554059, 165, 'WAL-MART<br/>1000 GRAVES ST.<br/>CHILLICOTHE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[164] = marker;
    marker = createLocationMarker(37.060088, -93.303387, 166, 'WAL-MART<br/>1102 NORTH MASSEY BLVD.<br/>NIXA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[165] = marker;
    marker = createLocationMarker(37.140756, -93.424872, 167, 'LOWE\'S OF REPUBLIC, MO<br/>1225 US HIGHWAY 60 EAST<br/>REPUBLIC');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[166] = marker;
    marker = createLocationMarker(39.003974, -93.953344, 168, 'WB #167 FELDMANS FARM & HOME - ODESSA<br/>304 NORTH 2ND STREET<br/>ODESSA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[167] = marker;
    marker = createLocationMarker(37.318953, -93.586975, 169, 'ASH GROVE TRUE VALUE<br/>307 PERRYMAN<br/>ASH GROVE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[168] = marker;
    marker = createLocationMarker(38.718197, -93.987324, 170, 'HEIMAN TRUE VALUE FARM SUPPLY<br/>201 S VINE ST<br/>HOLDEN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[169] = marker;
    marker = createLocationMarker(37.128525, -93.459044, 171, 'WAL-MART<br/>1150 US HWY 60 EAST<br/>REPUBLIC');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[170] = marker;
    marker = createLocationMarker(39.264072, -93.960897, 172, 'WAL-MART<br/>908 WALTON WAY<br/>RICHMOND');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[171] = marker;
    marker = createLocationMarker(39.276916, -93.976455, 173, 'LARRY\'S TRUE VALUE HARDWARE & APPLIANCES<br/>210 S THORNTON ST<br/>RICHMOND');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[172] = marker;
    marker = createLocationMarker(38.190605, -94.030967, 174, 'T-G TRUE VALUE HDW<br/>301 W 4TH ST<br/>APPLETON CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[173] = marker;
    marker = createLocationMarker(40.074371, -93.601107, 175, 'EASTERS TRUE VALUE<br/>1705 E 9TH ST<br/>TRENTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[174] = marker;
    marker = createLocationMarker(36.681047, -93.234793, 176, 'HOME DEPOT<br/>1000 BRANSON HILLS PKWY<br/>BRANSON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[175] = marker;
    marker = createLocationMarker(36.681047, -93.234793, 177, 'WAL-MART<br/>1101 BRANSON HILLS PKWY<br/>BRANSON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[176] = marker;
    marker = createLocationMarker(39.004701, -94.124406, 178, 'WAL-MART<br/>201 SOUTH SALEM STREET<br/>OAK GROVE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[177] = marker;
    marker = createLocationMarker(37.911226, -94.041564, 179, 'TAYLOR TRUE VALUE<br/>4950 E HWY 54<br/>EL DORADO SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[178] = marker;
    marker = createLocationMarker(36.612798, -93.228129, 180, 'LOWE\'S OF HOLLISTER, MO.<br/>165 MALL ROAD<br/>HOLLISTER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[179] = marker;
    marker = createLocationMarker(36.703478, -93.361297, 181, 'WAL-MART<br/>18401 STATE HWY 13<br/>BRANSON WEST');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[180] = marker;
    marker = createLocationMarker(36.677161, -93.390279, 182, 'WAL-MART<br/>2050 WEST HWY 76<br/>BRANSON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[181] = marker;
    marker = createLocationMarker(37.214842, -93.839958, 183, 'HUNT\'S HARDWARE<br/>205 E MAIN ST<br/>MILLER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[182] = marker;
    marker = createLocationMarker(39.025633, -94.250302, 184, 'HOME DEPOT<br/>905 ADAMS DAIRY PKWY<br/>BLUE SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[183] = marker;
    marker = createLocationMarker(38.73349, -94.280873, 185, 'MIDWEST LUMBER TRUE VALUE HOME CENTER<br/>2207 N STATE ROUTE 7<br/>PLEASANT HILL');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[184] = marker;
    marker = createLocationMarker(37.386568, -93.950197, 186, 'S&H TRUE VALUE HARDWARE<br/>7 ROUTE A<br/>LOCKWOOD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[185] = marker;
    marker = createLocationMarker(39.026919, -94.256332, 187, 'WAL-MART<br/>600 N.E. CORONADO DRIVE<br/>BLUE SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[186] = marker;
    marker = createLocationMarker(39.020567, -94.272108, 188, 'WB #237 FELDMANS F & H - BLUE SPRINGS<br/>310 SOUTH 7 HIGHWAY<br/>BLUE SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[187] = marker;
    marker = createLocationMarker(36.97037, -93.702981, 189, 'JOURNAGAN TRUE VALUE HDWE<br/>1200 E CHURCH ST<br/>AURORA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[188] = marker;
    marker = createLocationMarker(37.09439, -93.81458, 190, 'BRAD\'S TRUE VALUE HARDWARE<br/>530 EAST MT VERNON BLVD<br/>MOUNT VERNON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[189] = marker;
    marker = createLocationMarker(36.944873, -93.718682, 191, 'WAL-MART<br/>3020 SOUTH ELLIOTT<br/>AURORA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[190] = marker;
    marker = createLocationMarker(39.330165, -94.265104, 192, 'WAL-MART<br/>2203 PATSY LANE<br/>EXCELSIOR SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[191] = marker;
    marker = createLocationMarker(38.686943, -94.365062, 193, 'WAL-MART<br/>1700 NORTH 291 HIGHWAY<br/>HARRISONVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[192] = marker;
    marker = createLocationMarker(38.266887, -94.344376, 194, 'MIDWEST LUMBER & SUPPLY INC<br/>1007 N ORANGE<br/>BUTLER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[193] = marker;
    marker = createLocationMarker(38.900794, -94.361987, 195, 'HOME DEPOT<br/>651 SE OLDHAM PARKWAY<br/>LEES SUMMIT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[194] = marker;
    marker = createLocationMarker(38.927777, -94.359951, 196, 'SEARS<br/>601 NORTH M 291<br/>LEES SUMMIT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[195] = marker;
    marker = createLocationMarker(38.929718, -94.361177, 197, 'WAL-MART<br/>1000 NE SAM WALTON LANE<br/>LEE\'S SUMMIT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[196] = marker;
    marker = createLocationMarker(38.662519, -94.376674, 198, 'WB #137 FAMILY CENTER HARRISONVILLE MO<br/>2601 CANTRELL RD<br/>HARRISONVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[197] = marker;
    marker = createLocationMarker(38.257, -94.349734, 199, 'WAL-MART<br/>1005 W FT SCOTT<br/>BUTLER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[198] = marker;
    marker = createLocationMarker(39.034751, -94.356694, 200, 'LOWE\'S OF INDEPENDENCE, MO.<br/>19000 EAST VALLEY VIEW PARKWAY<br/>INDEPENDENCE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[199] = marker;
    marker = createLocationMarker(39.048009, -94.359574, 201, 'SEARS<br/>18777 E 39TH ST<br/>INDEPENDENCE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[200] = marker;
    marker = createLocationMarker(39.046482, -94.364552, 202, 'WAL-MART<br/>4000 SOUTH BOLGER DR<br/>INDEPENDENCE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[201] = marker;
    marker = createLocationMarker(39.042413, -94.387484, 203, 'HOME DEPOT<br/>4210 S LEE\'S SUMMIT RD<br/>INDEPENDENCE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[202] = marker;
    marker = createLocationMarker(38.926298, -94.411186, 204, 'LOWE\'S OF LEE\'S SUMMIT, MO<br/>1830 NORTHWEST CHIPMAN ROAD<br/>LEES SUMMIT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[203] = marker;
    marker = createLocationMarker(39.088522, -94.417249, 205, 'FREVERT TRUE VALUE HDW<br/>409 S STATE RTE 291<br/>LIBERTY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[204] = marker;
    marker = createLocationMarker(39.101975, -94.438384, 206, 'WAL-MART<br/>11601 EAST US 40 HIGHWAY<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[205] = marker;
    marker = createLocationMarker(39.756466, -94.234355, 207, 'WAL-MART<br/>2000 NORTH WALNUT<br/>CAMERON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[206] = marker;
    marker = createLocationMarker(36.913132, -93.864366, 208, 'WAL-MART<br/>885 HIGHWAY 60<br/>MONETT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[207] = marker;
    marker = createLocationMarker(38.81065, -94.493968, 209, 'LOWE\'S OF RAYMORE, MO<br/>225 NORTH DEAN AVENUE<br/>RAYMORE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[208] = marker;
    marker = createLocationMarker(38.812848, -94.494158, 210, 'WAL-MART<br/>2015 WEST FOXWOOD DR<br/>RAYMORE/BELTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[209] = marker;
    marker = createLocationMarker(39.001699, -94.480185, 211, 'WAL-MART<br/>6709 BLUE RIDGE BLVD.<br/>RAYTOWN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[210] = marker;
    marker = createLocationMarker(39.242631, -94.441549, 212, 'WB #275 FELDMANS FARM & HOME - LIBERTY<br/>300 SOUTH 291 HIGHWAY<br/>LIBERTY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[211] = marker;
    marker = createLocationMarker(39.246289, -94.451157, 213, 'LOWE\'S OF LIBERTY, MO<br/>1920 N. STEWART ROAD<br/>LIBERTY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[212] = marker;
    marker = createLocationMarker(38.81371, -94.515298, 214, 'HOME DEPOT<br/>1306 E NORTH AVENUE<br/>BELTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[213] = marker;
    marker = createLocationMarker(39.244591, -94.453166, 215, 'SEARS<br/>2001 W KANSAS ST<br/>LIBERTY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[214] = marker;
    marker = createLocationMarker(39.246059, -94.458776, 216, 'HOME DEPOT<br/>8598 N CHURCH RD<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[215] = marker;
    marker = createLocationMarker(39.242948, -94.459834, 217, 'WAL-MART<br/>8301 NO. CHURCH ROAD<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[216] = marker;
    marker = createLocationMarker(36.92241, -93.917257, 218, 'GLIEDT ELECTRIC<br/>914 BROADWAY<br/>MONETT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[217] = marker;
    marker = createLocationMarker(38.906128, -94.527453, 219, 'MIDLAND TRUE VALUE HDW<br/>12012 BLUE RIDGE EXT<br/>GRANDVIEW');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[218] = marker;
    marker = createLocationMarker(38.953224, -94.533466, 220, 'HOME DEPOT<br/>4707 E BANNISTER RD<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[219] = marker;
    marker = createLocationMarker(40.262452, -94.014711, 221, 'WAL-MART<br/>810 SO. 37TH ST.<br/>BETHANY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[220] = marker;
    marker = createLocationMarker(37.493289, -94.304146, 222, 'WAL-MART<br/>29 S.W. 1ST LANE<br/>LAMAR');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[221] = marker;
    marker = createLocationMarker(38.997632, -94.556693, 223, 'MIDLAND TRUE VALUE HDW<br/>7107 PROSPECT AVE<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[222] = marker;
    marker = createLocationMarker(39.042457, -94.572642, 224, 'MIDLAND TRUE VALUE HARDWARE<br/>4627 TROOST AVE<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[223] = marker;
    marker = createLocationMarker(39.190649, -94.54681, 225, 'SEARS<br/>5415 NW ANTIOCH RD<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[224] = marker;
    marker = createLocationMarker(37.068822, -94.116063, 226, 'C & C TRUE VALUE LUMBER CO<br/>108 S 5TH ST<br/>SARCOXIE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[225] = marker;
    marker = createLocationMarker(39.068415, -94.583763, 227, 'HOME DEPOT<br/>111 E LINWOOD AVE<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[226] = marker;
    marker = createLocationMarker(38.886568, -94.606324, 228, 'LOWE\'S OF S. KANSAS CITY, MO<br/>1770 W. 133RD STREET<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[227] = marker;
    marker = createLocationMarker(39.181979, -94.576574, 229, 'LOWE\'S OF KANSAS CITY (GLADSTONE), MO<br/>4811 NORTH OAK TRAFFICWAY<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[228] = marker;
    marker = createLocationMarker(39.335807, -94.544584, 230, 'WAL-MART<br/>1701 WEST 133RD STREET<br/>KANSAS CITY (S)');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[229] = marker;
    marker = createLocationMarker(39.184085, -94.58254, 231, 'HOME DEPOT<br/>4949 OLD PIKE RD<br/>GLADSTONE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[230] = marker;
    marker = createLocationMarker(36.688952, -93.875717, 232, 'WAL-MART<br/>10340 FARM ROAD 2176<br/>CASSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[231] = marker;
    marker = createLocationMarker(39.88951, -94.359435, 233, 'BAKERS TRUE VALUE HDW<br/>108 W MAIN ST<br/>MAYSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[232] = marker;
    marker = createLocationMarker(39.172348, -94.613292, 234, 'WAL-MART<br/>7207 NORTH M-1 HWY<br/>GLADSTONE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[233] = marker;
    marker = createLocationMarker(36.675655, -93.88277, 235, 'CASSVILLE TRUE VALUE HOME CENTER<br/>1011 OLD EXETER ROAD<br/>CASSVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[234] = marker;
    marker = createLocationMarker(39.223842, -94.650981, 236, 'SEARS<br/>7100 NW PRAIRIE VIEW ROAD<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[235] = marker;
    marker = createLocationMarker(39.252429, -94.652536, 237, 'LOWE\'S OF N KANSAS CITY, MO.<br/>8601 N. BOARDWALK AVENUE<br/>KANSAS CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[236] = marker;
    marker = createLocationMarker(39.252415, -94.653957, 238, 'WAL-MART<br/>8551 N.BOARDWALK AVE.<br/>KANSAS CITY (NW)');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[237] = marker;
    marker = createLocationMarker(37.177059, -94.310727, 239, 'CARTHAGE TRUE VALUE<br/>119 E 3RD ST<br/>CARTHAGE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[238] = marker;
    marker = createLocationMarker(37.142146, -94.310506, 240, 'WAL-MART<br/>2705 GRAND AVE<br/>CARTHAGE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[239] = marker;
    marker = createLocationMarker(37.140272, -94.315641, 241, 'LOWE\'S OF CARTHAGE, MO<br/>433 WEST FIR ROAD<br/>CARTHAGE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[240] = marker;
    marker = createLocationMarker(39.35184, -94.769056, 242, 'EGGEN\'S TRUE VALUE HDWE<br/>2300 KENTUCKY AVE<br/>PLATTE CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[241] = marker;
    marker = createLocationMarker(37.133585, -94.475156, 243, 'WAL-MART<br/>1212 SOUTH MADISON<br/>WEBB CITY');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[242] = marker;
    marker = createLocationMarker(37.069678, -94.476251, 244, 'HOME DEPOT<br/>3110 E 20TH STREET<br/>JOPLIN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[243] = marker;
    marker = createLocationMarker(37.060874, -94.47823, 245, 'LOWE\'S OF JOPLIN, MO.<br/>2600 RANGE LINE RD.<br/>JOPLIN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[244] = marker;
    marker = createLocationMarker(37.085222, -94.51345, 246, 'PEARL BROS TRUE VALUE HDW.<br/>617 MAIN ST<br/>JOPLIN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[245] = marker;
    marker = createLocationMarker(39.410534, -94.902247, 247, 'SEBUS BROTHERS TRUE VALUE<br/>405 MAIN ST<br/>WESTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[246] = marker;
    marker = createLocationMarker(36.838408, -94.391784, 248, 'LOWE\'S OF NEOSHO, MO<br/>1490 CLEMON DRIVE<br/>NEOSHO');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[247] = marker;
    marker = createLocationMarker(36.841486, -94.394412, 249, 'WAL-MART<br/>3200 LUSK DRIVE<br/>NEOSHO');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[248] = marker;
    marker = createLocationMarker(39.80406, -94.815022, 250, 'LOWE\'S OF ST. JOSEPH, MO.<br/>3901 N. BELT HWY.<br/>SAINT JOSEPH');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[249] = marker;
    marker = createLocationMarker(39.805398, -94.81505, 251, 'WAL-MART<br/>4201 N BELT HIGHWAY<br/>ST. JOSEPH');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[250] = marker;
    marker = createLocationMarker(39.690564, -94.867078, 252, 'DAVIS TRUE VALUE HDW<br/>238 HWY ST<br/>DONIPHAN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[251] = marker;
    marker = createLocationMarker(36.650851, -94.441368, 253, 'COAST TO COAST<br/>122 MAIN ST<br/>ANDERSON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[252] = marker;
    marker = createLocationMarker(40.326382, -94.873954, 254, 'WAL-MART<br/>1605 S MAIN ST<br/>MARYVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[253] = marker;
    marker = createLocationMarker(38.959657, -77.02416, 255, 'LOWE\'S OF WASHINGTON, MO<br/>2023 WASHINGTON CROSSING<br/>WASHINGTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[254] = marker;
    marker = createLocationMarker(0, 0, 256, 'LOWE\'S OF ARNOLD, MO<br/>920 ARNOLD COMMONS<br/>ARNOLD');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[255] = marker;
    marker = createLocationMarker(0, 0, 257, 'LOWE\'S OF OZARK, MO<br/>1800 WEST MARLER LANE<br/>OZARK');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[256] = marker;
    marker = createLocationMarker(0, 0, 258, 'LOWE\'S OF ST. ROBERT, MO<br/>120 CARSON BOULEVARD<br/>SAINT ROBERT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[257] = marker;
    marker = createLocationMarker(0, 0, 259, 'LOWE\'S OF MONETT, MO<br/>925 EAST US HIGHWAY 60<br/>MONETT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[258] = marker;
    marker = createLocationMarker(0, 0, 260, 'WATKINS TRUE VALUE HDW. & APPL.<br/>1416 S MAIN MARY MART CTR<br/>MARYVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[259] = marker;
    marker = createLocationMarker(0, 0, 261, 'FETTERHOFFS TRUE VALUE HDW<br/>313 S FIRST ST<br/>MARBLE HILL');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[260] = marker;
    marker = createLocationMarker(0, 0, 262, 'NEOSHO TRUE VALUE HARDWARE<br/>1725 LAQUESTA DR<br/>NEOSHO');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[261] = marker;
    marker = createLocationMarker(0, 0, 263, 'HANDYMAN TRUE VALUE HARDWARE<br/>2635 N US HWY 67<br/>FLORISSANT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[262] = marker;
    marker = createLocationMarker(0, 0, 264, 'WB #123 EDINA FARM & HOME<br/>HIGHWAY 6 & 15 SOUTH<br/>EDINA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[263] = marker;
    marker = createLocationMarker(0, 0, 265, 'DICKEY BUB TRUE VALUE<br/>HWY 8 & TRIMFOOT RD<br/>POTOSI');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[264] = marker;
    marker = createLocationMarker(0, 0, 266, 'WAGGONER TRUE VALUE HOME CENTER<br/>1123 W BUSINESS 60-63<br/>WILLOW SPRINGS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[265] = marker;
    marker = createLocationMarker(0, 0, 267, 'JOHNSON TRUE VALUE<br/>HWY 34 EAST<br/>PIEDMONT');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[266] = marker;
    marker = createLocationMarker(0, 0, 268, 'TRUE VALUE BUILDING SUPPLIES<br/>RR 3 - BOX 3022<br/>ALTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[267] = marker;
    marker = createLocationMarker(0, 0, 269, 'WAL-MART<br/>855 S CHEROKEE DRIVE<br/>MARSHALL');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[268] = marker;
    marker = createLocationMarker(0, 0, 270, 'WAL-MART<br/>3310 W GEORGIA STREET<br/>LOUISIANA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[269] = marker;
    marker = createLocationMarker(0, 0, 271, 'WAL-MART<br/>1007 NORTH DOUGLAS<br/>MALDEN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[270] = marker;
    marker = createLocationMarker(0, 0, 272, 'WAL-MART<br/>1025 WALTON DRIVE<br/>FREDERICKTOWN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[271] = marker;
    marker = createLocationMarker(0, 0, 273, 'WAL-MART<br/>1501 SOUTH RANGELINE ROAD<br/>JOPLIN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[272] = marker;
    marker = createLocationMarker(0, 0, 274, 'WAL-MART<br/>2623 WEST 7TH STREET<br/>JOPLIN (W)');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[273] = marker;
    marker = createLocationMarker(0, 0, 275, 'WAL-MART<br/>3022 SOUTH BELT HWY<br/>ST. JOSEPH (S)');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[274] = marker;
    marker = createLocationMarker(0, 0, 276, 'WAL-MART<br/>1661 JUNGERMAN RD<br/>ST. PETERS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[275] = marker;
    marker = createLocationMarker(0, 0, 277, 'WAL-MART<br/>350 PARKRIDGE ROAD<br/>SULLIVAN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[276] = marker;
    marker = createLocationMarker(0, 0, 278, 'WAL-MART<br/>1923 EAST KEARNEY<br/>SPRINGFIELD (NE)');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[277] = marker;
    marker = createLocationMarker(0, 0, 279, 'WAL-MART<br/>2250 LINCOLN AVENUE<br/>NEVADA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[278] = marker;
    marker = createLocationMarker(0, 0, 280, 'WAL-MART<br/>101 W HIGHWAY 60<br/>MOUNTAINVIEW');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[279] = marker;
    marker = createLocationMarker(0, 0, 281, 'WAL-MART<br/>2004 WEST MARLER LANE<br/>OZARK');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[280] = marker;
    marker = createLocationMarker(0, 0, 282, 'WAL-MART<br/>#1 MEMORIAL DRIVE<br/>POTOSI');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[281] = marker;
    marker = createLocationMarker(0, 0, 283, 'WAL-MART<br/>100 COMMERCIAL DRIVE<br/>PINEVILLE');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[282] = marker;
    marker = createLocationMarker(0, 0, 284, 'WAL-MART<br/>3439 WILLIAMS STREET<br/>CAPE GIRARDEAU');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[283] = marker;
    marker = createLocationMarker(0, 0, 285, 'WAL-MART<br/>1802 SOUTH BUSINESS HWY 54<br/>ELDON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[284] = marker;
    marker = createLocationMarker(0, 0, 286, 'WAL-MART<br/>131 ERKA TWN CNTR DR<br/>EUREKA');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[285] = marker;
    marker = createLocationMarker(0, 0, 287, 'SEARS<br/>WESTFIELD SOUTH COUNTY S/C, 250 SOUTH COUNTY CENTERWAY<br/>SAINT LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[286] = marker;
    marker = createLocationMarker(0, 0, 288, 'SEARS<br/>#3 MID RIVER MALL, 1600 MID RIVER MALL DRIVE<br/>SAINT PETERS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[287] = marker;
    marker = createLocationMarker(0, 0, 289, 'WAL-MART<br/>94 CECIL STREET<br/>CAMDENTON');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[288] = marker;
    marker = createLocationMarker(0, 0, 290, 'SEARS<br/>700 N W PLAZA S/C<br/>SAINT ANN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[289] = marker;
    marker = createLocationMarker(0, 0, 291, 'SEARS<br/>101 S RANGELINE ROAD<br/>JOPLIN');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[290] = marker;
    marker = createLocationMarker(0, 0, 292, 'HOME DEPOT<br/>7481 S LINDBERG BLVD<br/>SAINT LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[291] = marker;
    marker = createLocationMarker(0, 0, 293, 'HOME DEPOT<br/>5201 N BELT LINE HWY<br/>ST JOSEPH');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[292] = marker;
    marker = createLocationMarker(0, 0, 294, 'HOME DEPOT<br/>3202 S KINGS HWY BLVD<br/>ST LOUIS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[293] = marker;
    marker = createLocationMarker(0, 0, 295, 'HOME DEPOT<br/>6190 MID RIVER MALL DR<br/>ST PETER');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[294] = marker;
    marker = createLocationMarker(0, 0, 296, 'WAL-MART<br/>103 WEST POLK ST<br/>WARSAW');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[295] = marker;
    marker = createLocationMarker(0, 0, 297, 'WAL-MART<br/>1310 PREACHER RD/HGWY 160<br/>WEST PLAINS');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[296] = marker;
    marker = createLocationMarker(0, 0, 298, 'WAL-MART<br/>3520 W SUNSHINE ST.<br/>SPRINGFIELD (WEST)');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[297] = marker;
    marker = createLocationMarker(0, 0, 299, 'WAL-MART<br/>PO BOX 12-1003 WEST NEWTON ST<br/>VERSAILLES');
    var myPoint = marker.getPoint();
    map.setCenter(myPoint, 13);
    map.addOverlay(marker);
    arr[298] = marker;
    displayInfo();
    displayMap();
    map.checkResize();
    var bounds = getBounds(map.getCurrentMapType(), map.getSize(), arr);
    map.setCenter(bounds.getCenter(), map.getBoundsZoomLevel(bounds) - 1);
    for (var i = 0; i < length; i++) {
        currentlyMappedLabels[i].className = 'hideCurrentlyMapped';
    }
}

map.setMapType(G_NORMAL_MAP);

function displayInfo(allLabel, label, scrollLabel, mapLink){
    //var allLabel = document.getElementById('dnn_ctr385_MainDisplay_lblLocatorMapLabel');
    allLabel.style.display = '';
    //var label = document.getElementById('locatorMapLabel');
    label.style.display = 'none';
    //var scrollLabel = document.getElementById('dnn_ctr385_MainDisplay_lblScrollToViewMore');
    scrollLabel.style.display = 'none';
    //var mapLink = document.getElementById('lblMapLink');
    mapLink.style.display = 'none';
    //var currentlyMappedLabels = getElementsByClassName('currentlyMapped', 'span', document.getElementById('dnn_ctr385_MainDisplay_rptLocations'));
    //var length = currentlyMappedLabels.length;
}

function getBounds(mapType, size, arr){
    var south, west, east, north;
    south = west = 180;
    east = north = -180;
    for (var i = 0; i < arr.length; i++) {
        if (arr[i].getPoint().lat() > north) {
            north = arr[i].getPoint().lat();
        }
        if (arr[i].getPoint().lat() < south) {
            south = arr[i].getPoint().lat();
        }
        if (arr[i].getPoint().lng() > east) {
            east = arr[i].getPoint().lng();
        }
        if (arr[i].getPoint().lng() < west) {
            west = arr[i].getPoint().lng();
        }
    }
    var southWest = new GLatLng(south, west);
    var northEast = new GLatLng(north, east);
    var bounds = new GLatLngBounds(southWest, northEast);
    var zoomLevel = mapType.getBoundsZoomLevel(bounds, map.getSize());
    var minZoom = mapType.getMinimumResolution(arr[0]);
    if (zoomLevel < minZoom) {
        zoomLevel = minZoom;
    }
    return bounds;
}

function createCenterMarker(latitude, longitude){
    var myPoint = new GLatLng(latitude, longitude);
    var myImage = new GIcon();
    myImage.image = "/images/ratingminus.gif";
    myImage.iconSize = new GSize(18, 18);
    myImage.iconAnchor = new GPoint(0, 0);
    var marker = new GMarker(myPoint, myImage);
    return marker;
}

function createLocationMarker(latitude, longitude, index, address){
    var myPoint = new GLatLng(latitude, longitude);
    var marker = new GMarker(myPoint);
    GEvent.addListener(marker, "click", function(){
        marker.openInfoWindowHtml(index + ") " + address.replace("%%", "<br />"));
    });
    return marker;
}

function getElementsByClassName(className, tag, elm){
    var returnElements;
    if (node.getElementsByClassName) {
        returnElements = node.getElementsByClassName(classname);
        if (tag && tag !== '*') {
            returnElements = Array.filter(returnElements, function(elem){
                return elem.nodeName === tag.toUpperCase();
            });
        }
    }
    else {
        var testClass = new RegExp("(^|\s)" + className + "(\s|$)");
        var tag = tag || "*";
        var elm = elm || document;
        var elements = (tag == "*" && elm.all) ? elm.all : elm.getElementsByTagName(tag);
        returnElements = [];
        var current;
        var length = elements.length;
        for (var i = 0; i < length; i++) {
            current = elements[i];
            if (testClass.test(current.className)) {
                returnElements.push(current);
            }
        }
    }
    return returnElements
}
